export const GET_EMPLOYEES_LIST = "GET_EMPLOYEES_LIST";
export const GET_EMPLOYEES_LIST_SUCCESS = "GET_EMPLOYEES_LIST_SUCCESS";

export const Add_EMPLOYEE = "Add_EMPLOYEE";
export const Add_EMPLOYEE_SUCCESS = "Add_EMPLOYEE_SUCCESS";

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";